// Generated by CoffeeScript 1.12.4
(function() {
  var CellListField, ColumnChartField, FUDGE_FACTOR, SignatureField, isScrollVisible, root,
    slice = [].slice,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  FUDGE_FACTOR = 5;

  isScrollVisible = function(elem) {
    var docViewBottom, docViewTop, elemBottom, elemTop;
    if ($(elem).height() === 0) {
      return false;
    }
    docViewTop = $(window).scrollTop();
    docViewBottom = docViewTop + $(window).height();
    elemTop = $(elem).offset().top;
    elemBottom = elemTop + $(elem).height();
    return (elemBottom <= docViewBottom) && (elemTop >= docViewTop);
  };

  $(function() {
    var resizer;
    resizer = function() {
      var celllist, celllists, cl, id, k, len, results;
      if (isMobileWidth()) {
        return;
      }
      celllists = $('body').find('.celllist.autoheight');
      results = [];
      for (k = 0, len = celllists.length; k < len; k++) {
        celllist = celllists[k];
        id = celllist.id;
        cl = __Fields__[id];
        if (cl != null) {
          results.push(cl.adjustHeight());
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    if (typeof window !== "undefined" && window !== null) {
      return $(window).resize(_.throttle(resizer, 500, {
        leading: false
      }));
    }
  });

  CellListField = (function() {
    CellListField.currentCellList = function(hr) {
      var celllist;
      celllist = $(hr).parents('.celllist').attr('id');
      return __Fields__[celllist];
    };

    CellListField.updateCurrentCell = function(hr) {
      var celllist, ref, rowid;
      rowid = $(hr).parents('li.celllist-cell').attr('rowid');
      celllist = $(hr).parents('.celllist').attr('id');
      if (xint(rowid) > 0) {
        return (ref = __Fields__[celllist]) != null ? ref.updateCell(rowid) : void 0;
      }
    };

    function CellListField(id1, opts1) {
      this.id = id1;
      this.opts = opts1 != null ? opts1 : null;
      this.parametersRequiredFuncs = [];
      this.requestQueue = [];
      this.bindAll();
      this.sortOrder = 'ascending';
      $((function(_this) {
        return function() {
          var adjuster, el;
          el = _this.ctrl();
          if (el.hasClass('autoheight')) {
            el.addClass('ontabselected');
            adjuster = function() {
              return _this.adjustHeight();
            };
            el.bind('tabselected', _.throttle(adjuster, 500, {
              leading: false
            }));
            return adjuster();
          }
        };
      })(this));
    }

    CellListField.prototype.getContents = function() {
      return this.ctrl().find('li.celllist-cell');
    };

    CellListField.prototype.registerChangeEvent = function(f) {
      var doit;
      doit = function(e, cell) {
        return _.defer(function() {
          return f(cell);
        });
      };
      return $(this).bind('celllist.changed', doit);
    };

    CellListField.prototype.adjustHeight = function() {
      var diff, el, height, top;
      el = this.ctrl();
      height = $(window).height();
      top = el.offset().top;
      diff = height - top;
      return el.height(diff + 'px');
    };

    CellListField.prototype.ctrl = function() {
      return $$(this.id);
    };

    CellListField.prototype.init = function() {
      this.updateCounter();
      this.setupSorter();
      this.registerChangeEvents();
      if (this.opts.async) {
        return _.defer((function(_this) {
          return function() {
            return _this.loadFresh();
          };
        })(this));
      }
    };

    CellListField.prototype.parametersRequired = function(func) {
      return this.parametersRequired.push(func);
    };

    CellListField.prototype.clearNoData = function() {
      var ctrl;
      ctrl = this.ctrl();
      $(ctrl).find('.nodataresults').makeInvisible();
      return $(ctrl).find('.nomoredataresults').makeInvisible();
    };

    CellListField.prototype.setNoData = function() {
      var ctrl, items;
      ctrl = this.ctrl();
      items = $(ctrl).find('li.celllist-cell');
      if (items.length === 0) {
        $(ctrl).find('.nodataresults').makeVisible();
        return $(ctrl).find('.nomoredataresults').makeInvisible();
      } else {
        $(ctrl).find('.nodataresults').makeInvisible();
        return $(ctrl).find('.nomoredataresults').makeVisible();
      }
    };

    CellListField.prototype.checkAndLoadMore = function() {
      var ctrl, load_more;
      ctrl = this.ctrl();
      load_more = ctrl.find('.loadmore');
      if (load_more.hasClass('loading')) {
        return;
      }
      if (isScrollVisible(load_more)) {
        console.log('Loading icon visible. Loading more...');
        return this.loadMore();
      }
    };

    CellListField.prototype.bindAll = function() {
      var can_resize, counterUpdater, ctrl, scrollOffset, self, throttledCounterUpdate;
      self = this;
      scrollOffset = 0.8;
      ctrl = this.ctrl();
      ctrl.find('.results').setupCustomScrolling();
      counterUpdater = (function(_this) {
        return function() {
          return _this.updateCounter();
        };
      })(this);
      throttledCounterUpdate = _.debounce(counterUpdater, 400);
      $('.more.top', ctrl).click(function(evnt) {
        var height, offset, p, x;
        height = self.getCellHeight();
        if (height <= 0) {
          height = 50;
        }
        evnt.preventDefault();
        x = $(this);
        p = x.parent('.celllist').find('.results');
        offset = height * Math.floor(-1 + (p.height() / height));
        return p.animate({
          scrollTop: p.scrollTop() - offset
        }, {});
      });
      $('.more.bottom', ctrl).click(function(evnt) {
        var height, offset, p, x;
        height = self.getCellHeight();
        if (height <= 0) {
          height = 50;
        }
        evnt.preventDefault();
        x = $(this);
        p = x.parent('.celllist').find('.results');
        offset = height * Math.floor(-1 + (p.height() / height));
        return p.animate({
          scrollTop: p.scrollTop() + offset
        }, {});
      });
      ctrl.find('.results').bind('scroll', (function(_this) {
        return function(evnt) {
          throttledCounterUpdate();
          return _this.checkAndLoadMore();
        };
      })(this));
      this.loadMoreCtrl().click((function(_this) {
        return function(evnt) {
          evnt.preventDefault();
          if ($(_this).hasClass('loading')) {
            return;
          }
          return _this.loadMore();
        };
      })(this));
      can_resize = this.ctrl().hasClass('autoresize');
      if (can_resize) {
        return this.ctrl().bind('webletsizechanged', function(evnt, new_cls, old_cls) {
          if (new_cls === 1 || new_cls === 2) {
            self.reCol(1);
            return;
          }
          if (new_cls === 3) {
            self.reCol(2);
            return;
          }
          if (new_cls === 4) {
            self.reCol(4);
          }
        });
      }
    };

    CellListField.prototype.clearLoading = function() {
      return this.ctrl().find('.resultcontainer ul').empty();
    };

    CellListField.prototype.registerChangeEvents = function() {
      var ab, f, k, len, loader, param, ref, ref1, reload, so;
      loader = (function(_this) {
        return function() {
          return _this.loadFresh();
        };
      })(this);
      reload = _.debounce(loader, 400);
      ref1 = (ref = this.opts) != null ? ref.parameters : void 0;
      for (k = 0, len = ref1.length; k < len; k++) {
        param = ref1[k];
        f = this.getFieldID(param);
        ab = param.auto_bind;
        if (ab !== '0') {
          ServiceDesk.registerFieldChange(f, function() {
            return reload();
          });
        }
      }
      if (this.sortSelector != null) {
        this.sortSelector.on('change', (function(_this) {
          return function() {
            return reload();
          };
        })(this));
      }
      if (this.sortOrderSelector != null) {
        so = this.sortOrderSelector;
        return so.touchClick((function(_this) {
          return function(e) {
            _this.sortOrder = 'ascending';
            if (so.hasClass('ascending')) {
              so.removeClass('ascending');
              so.addClass('descending');
              _this.sortOrder = 'descending';
            } else {
              so.removeClass('descending');
              so.addClass('ascending');
              _this.sortOrder = 'ascending';
            }
            return reload();
          };
        })(this));
      }
    };

    CellListField.prototype.loadFresh = function() {
      return this.loadMore({
        clear: true
      });
    };

    CellListField.prototype.reloadCurrent = function(opts) {
      var rowid;
      opts = opts || {};
      rowid = xint(this.topVisibleCell().attr('rowid'));
      opts.from = rowid - 1;
      opts.clear = true;
      return this.loadMore(opts);
    };

    CellListField.prototype.updateField = function(opts) {
      return this.reloadCurrent(opts);
    };

    CellListField.prototype.getFieldID = function(parameter) {
      var ref, xf, xs;
      if (parameter.field) {
        return parameter.field;
      }
      xf = parameter.xfield;
      if (!xf) {
        return '';
      }
      xs = (ref = this.opts) != null ? ref.xscope : void 0;
      return $X(xs, xf);
    };

    CellListField.prototype.loadFilterParams = function(last, include_count) {
      var f, k, l, len, len1, n, param, params, ref, ref1, ref2, v;
      params = {
        __ajax__: '1',
        __sc__: __token__ || '',
        __celllistid__: this.id,
        __celllistmode__: 'next',
        last: last,
        __includetotalcount__: include_count
      };
      ServiceDesk.fillRemoteCallParams(params);
      ref1 = (ref = this.opts) != null ? ref.parameters : void 0;
      for (k = 0, len = ref1.length; k < len; k++) {
        param = ref1[k];
        f = this.getFieldID(param);
        n = param.name;
        v = param.value;
        if (f && n) {
          params[n] = xstr(v);
          ServiceDesk.gatherFieldValues(f, n, params);
        }
        if (n && v) {
          params[n] = v;
        }
      }
      ref2 = this.parametersRequiredFuncs;
      for (l = 0, len1 = ref2.length; l < len1; l++) {
        f = ref2[l];
        f(param);
      }
      if (this.sortSelector != null) {
        v = this.sortSelector.find('select').val();
        if (!!v) {
          params.__sort__ = v;
          params.__sortattrlist__ = 'all';
          params.__sortorder__ = this.sortOrder;
        }
      }
      return params;
    };

    CellListField.prototype.getSortInfo = function() {
      return {
        sortAttribute: this.sortSelector.find('select').val(),
        ascending: this.sortOrder === 'ascending',
        sortOrder: this.sortOrder
      };
    };

    CellListField.prototype.updateCell = function(rowid) {
      var params, url;
      url = this.ctrl().attr('view');
      params = this.loadFilterParams(xint(rowid) - 1, 0);
      params.max = 1;
      return $.ajax({
        type: 'post',
        url: url,
        data: params,
        success: (function(_this) {
          return function(data) {
            var cc, item, new_uid, old, old_uid, xi;
            $(_this).trigger('celllist.changed', [_this]);
            item = $(data).find('li.celllist-cell').get(0);
            if (item == null) {
              return;
            }
            xi = $(item);
            old = _this.ctrl().find('li.celllist-cell[rowid="' + rowid + '"]').get(0);
            old_uid = $(old).attr('unique_key');
            new_uid = $(xi).attr('unique_key');
            if (old_uid !== new_uid) {
              cc = _this.currentColCount();
              old.remove();
              return _this.reCol(cc, true);
            } else {
              return $(old).replaceWith(xi);
            }
          };
        })(this),
        error: function(request, status, _e) {
          return console.log('Error', request, status, _e);
        }
      });
    };

    CellListField.prototype.loadMore = function(fopts) {
      var oldDone, opts;
      opts = _.clone(fopts != null ? fopts : {});
      oldDone = opts != null ? opts.done : void 0;
      opts.done = (function(_this) {
        return function() {
          var args, nextOpts;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          if (typeof oldDone === "function") {
            oldDone.apply(null, args);
          }
          Array.removeItem(_this.requestQueue, fopts);
          if (_this.requestQueue.length > 0) {
            if (_this.requestQueue.length !== 1) {
              console.log('Warning: Request queue is large:' + _this.requestQueue);
            }
            nextOpts = _this.requestQueue.pop();
            if (nextOpts != null) {
              return _this.loadMore(nextOpts);
            }
          }
        };
      })(this);
      if (this.requestQueue.length > 0) {
        if (this.requestQueue.length !== 1) {
          console.log('Warning: Request queue already has too many items:' + this.requestQueue);
        }
        console.log('discarding old items', this.requestQueue);
        Array.removeAllItems(this.requestQueue);
        this.requestQueue.push(fopts);
        return;
      }
      this.requestQueue.push(fopts);
      return this.loadMoreQueued(opts);
    };

    CellListField.prototype.loadMoreQueued = function(fopts) {
      var cb, cell, cells, clear, from, include_count, items_to_clear, k, last, len, loader, nohighlight, params, ref, ref1, ref2, ref3, url;
      fopts = fopts || {};
      clear = (ref = fopts.clear) != null ? ref : false;
      from = (ref1 = fopts.from) != null ? ref1 : null;
      cb = (ref2 = fopts.done) != null ? ref2 : null;
      nohighlight = (ref3 = fopts.nohighlight) != null ? ref3 : false;
      if (!nohighlight) {
        loader = this.loadMoreCtrl();
        loader.addClass('loading');
        loader.makeVisible();
      }
      url = this.ctrl().attr('view');
      last = '0';
      include_count = '0';
      if (!clear) {
        last = this.lastItem();
      }
      items_to_clear = [];
      if (clear) {
        if (from != null) {
          last = '' + from;
          cells = this.ctrl().find('li.celllist-cell');
          for (k = 0, len = cells.length; k < len; k++) {
            cell = cells[k];
            if (xint($(cell).attr('rowid')) > from) {
              $(cell).addClass('empty');
              items_to_clear.push($(cell));
            }
          }
        } else {
          this.clearLoading();
        }
        include_count = '1';
      }
      params = this.loadFilterParams(last, include_count);
      this.clearNoData(last, include_count);
      return $.ajax({
        type: 'post',
        url: url,
        data: params,
        success: (function(_this) {
          return function(data) {
            var item, items, l, len1, len2, len3, m, node, q, script, scripts;
            $(_this).trigger('celllist.changed', [_this]);
            items = $(data).find('li.celllist-cell');
            if (clear) {
              _this.totalCount = 0;
            }
            if (items.length === 0) {
              if (loader != null) {
                loader.makeInvisible();
              }
              _this.setNoData();
              _this.updateCounter();
              for (l = 0, len1 = items_to_clear.length; l < len1; l++) {
                item = items_to_clear[l];
                item.remove();
              }
              if (typeof cb === "function") {
                cb(null);
              }
              return;
            }
            if (clear) {
              _this.totalCount = $(items[0]).attr('totalcount');
            }
            if (loader != null) {
              loader.makeVisible();
            }
            _this.clearNoData();
            _this.updateCounter();
            _this.addItems(items);
            for (m = 0, len2 = items_to_clear.length; m < len2; m++) {
              item = items_to_clear[m];
              item.remove();
            }
            if ((_this.opts.max != null) && (_this.opts.max * 0.9 > items.length)) {
              if (loader != null) {
                loader.makeInvisible();
              }
              _this.setNoData();
            }
            scripts = (function() {
              var len3, q, ref4, results;
              ref4 = $(data);
              results = [];
              for (q = 0, len3 = ref4.length; q < len3; q++) {
                node = ref4[q];
                if (node.nodeName === 'SCRIPT') {
                  results.push($(node).text());
                }
              }
              return results;
            })();
            for (q = 0, len3 = scripts.length; q < len3; q++) {
              script = scripts[q];
              eval(script);
            }
            if (typeof cb === "function") {
              cb(null);
            }
            return _this.checkAndLoadMore();
          };
        })(this),
        error: (function(_this) {
          return function(request, status, _e) {
            console.log('Error', request, status, _e);
            return typeof cb === "function" ? cb(_e) : void 0;
          };
        })(this)
      });
    };

    CellListField.prototype.lastItem = function() {
      var last_element;
      last_element = _.max(this.ctrl().find('.celllist-cell:not(".empty")'), function(x) {
        return xint($(x).attr('rowid'));
      });
      return $(last_element).attr('rowid');
    };

    CellListField.prototype.loadMoreCtrl = function() {
      return this.ctrl().find('.loadmore');
    };

    CellListField.prototype.addItems = function(items) {
      var col, cols, i, item, j, k, l, len, len1, loader, offset, start_col;
      cols = this.ctrl().find('.celllist-column');
      for (k = 0, len = cols.length; k < len; k++) {
        col = cols[k];
        $(col).find('li.empty').remove();
      }
      start_col = _.min(cols, function(c) {
        return $(c).find('li').length;
      });
      offset = _.indexOf(cols, start_col);
      for (j = l = 0, len1 = items.length; l < len1; j = ++l) {
        item = items[j];
        i = j + offset;
        col = $(cols[i % cols.length]);
        col.append(item);
      }
      loader = this.loadMoreCtrl();
      return loader.removeClass('loading');
    };

    CellListField.prototype.currentColCount = function() {
      var ctrl, current_cols;
      ctrl = this.ctrl().find('.resultcontainer');
      current_cols = ctrl.find('ul.celllist-column');
      return current_cols.length;
    };

    CellListField.prototype.reCol = function(cols, force) {
      var ci, col, col_items, col_set, ctrl, current_cols, i, items, k, l, len, m, ref, ref1, total, ul, width;
      if (force == null) {
        force = false;
      }
      if (cols < 1) {
        return;
      }
      if (cols > 6) {
        return;
      }
      ctrl = this.ctrl().find('.resultcontainer');
      current_cols = ctrl.find('ul.celllist-column');
      if (cols === current_cols.length && !force) {
        return;
      }
      col_items = [];
      total = 0;
      for (k = 0, len = current_cols.length; k < len; k++) {
        col = current_cols[k];
        ci = $(col).find('li.celllist-cell:not("empty")');
        total += ci.length;
        col_items.push(ci);
      }
      items = [];
      if (total > 0) {
        for (i = l = 0, ref = total - 1; 0 <= ref ? l <= ref : l >= ref; i = 0 <= ref ? ++l : --l) {
          col_set = col_items[i % current_cols.length];
          if (col_set.length === 0) {
            continue;
          }
          items.push(col_set.get(0));
          col_set.splice(0, 1);
        }
      }
      $(current_cols).remove();
      width = (100.0 / cols) + '%';
      if (cols > 0) {
        for (i = m = 0, ref1 = cols - 1; 0 <= ref1 ? m <= ref1 : m >= ref1; i = 0 <= ref1 ? ++m : --m) {
          ul = $('<ul />').addClass('celllist-column').css('width', width);
          if ((i + 1) % 2 === 0) {
            ul.addClass('celllist-column-even');
          } else {
            ul.addClass('celllist-column-odd');
          }
          ctrl.append(ul);
        }
      }
      return this.addItems(items);
    };

    CellListField.prototype.getCellHeight = function() {
      var r;
      r = this.ctrl().find('.results');
      if (this.cellHeight == null) {
        this.cellHeight = r.find('li.celllist-cell:first').height();
      }
      return this.cellHeight;
    };

    CellListField.prototype.topVisibleCell = function() {
      var bottom, el, k, len, li, lis;
      el = this.ctrl();
      lis = el.find('li.celllist-cell');
      for (k = 0, len = lis.length; k < len; k++) {
        li = lis[k];
        bottom = $(li).position().top + $(li).height();
        if (bottom > 0 + FUDGE_FACTOR) {
          return $(li);
        }
      }
      return $(lis.get(0));
    };

    CellListField.prototype.findTopElement = function() {
      var cellHeight, final, r, rc, top;
      r = this.ctrl().find('.results');
      rc = this.ctrl().find('.results .resultcontainer');
      cellHeight = this.getCellHeight();
      if ((cellHeight == null) || cellHeight === 0) {
        return [-1, -1];
      }
      top = -rc.position().top / cellHeight;
      top = Math.floor(top + 1);
      final = top - 1 + r.height() / cellHeight;
      if (final > this.totalCount) {
        final = this.totalCount;
      }
      return [top, final];
    };

    CellListField.prototype.setupSorter = function() {
      var a, k, len, o, s, so, sortAttrs, sortel, sp, util;
      sortAttrs = this.opts.sortattributes;
      if (!sortAttrs) {
        return;
      }
      util = $$(this.id + '__util');
      sortel = util.find('.celllist-sorter');
      sp = $('<span class="lbl" />');
      sp.text($L('sys.field-celllist-sort') + ':');
      sortel.append(sp);
      s = $('<select />');
      sortel.append(s);
      for (k = 0, len = sortAttrs.length; k < len; k++) {
        a = sortAttrs[k];
        o = $('<option />');
        o.attr('value', a.attribute);
        o.text(a.label);
        if (a.selected) {
          o.attr('selected', 'selected');
          this.sortOrder = a.ascending ? 'ascending' : 'descending';
        }
        s.append(o);
      }
      this.sortSelector = sortel;
      so = $('<span />');
      so.addClass('order');
      so.addClass(this.sortOrder);
      so.text(' ');
      sortel.append(so);
      return this.sortOrderSelector = so;
    };

    CellListField.prototype.updateCounter = function() {
      var computedTop, counter, final, ref, ref1, top, txt;
      counter = $$(this.id + '__counter');
      txt = '';
      if (this.totalCount) {
        txt = this.totalCount + ' ' + $L('sys.field-celllist-results');
        if (this.totalCount < 0) {
          txt = $L('sys.field-celllist-too-many-results');
        }
      }
      ref = this.findTopElement(), top = ref[0], final = ref[1];
      if (top >= 0 && this.totalCount > 0) {
        computedTop = top;
        if (top > 1) {
          computedTop = top * ((ref1 = this.currentColCount()) != null ? ref1 : 1);
        }
        txt = computedTop + ' of ' + txt;
      }
      return counter.text(txt);
    };

    CellListField.prototype.startBrowsing = function(ctrl, key) {};

    CellListField.prototype.exportToExcel = function(service) {
      var params, url;
      params = this.loadFilterParams(0, 0);
      params.__format__ = 'excel';
      params.__sc__ = __token__;
      params.__celllistmode__ = 'export.excel';
      params.__filename__ = 'export';
      url = this.ctrl().attr('view');
      url = ServiceDesk.addQueryString(url, params);
      return location.href = url;
    };

    return CellListField;

  })();

  SignatureField = (function() {
    function SignatureField(id1, opts1) {
      var closer, original_val;
      this.id = id1;
      this.opts = opts1;
      original_val = $$(this.id + '_val').val();
      $$(this.id).signaturePad({
        validateFields: false,
        drawOnly: true,
        canvas: 'canvas',
        output: '#' + this.id + '_val',
        displayOnly: this.opts.readonly === 'true'
      });
      closer = $$(this.id).find('.clearsig');
      closer.touchClick((function(_this) {
        return function(evnt) {
          evnt.preventDefault();
          return _this.clear();
        };
      })(this));
      if (this.opts.readonly === 'true') {
        closer.makeInvisible();
      }
      this.setValue(original_val);
    }

    SignatureField.prototype.sig = function() {
      return $$(this.id).signaturePad();
    };

    SignatureField.prototype.getValue = function() {
      return this.sig().getSignatureString();
    };

    SignatureField.prototype.setValue = function(data) {
      var ref, ref1;
      if (!data) {
        return (ref = this.sig()) != null ? ref.clearCanvas() : void 0;
      } else {
        return (ref1 = this.sig()) != null ? ref1.regenerate(data) : void 0;
      }
    };

    SignatureField.prototype.gatherPostFields = function(p) {
      return p[this.id + '_val'] = this.getValue();
    };

    SignatureField.prototype.gatherFields = function(p, n) {
      return p[n + this.id + '_val'] = this.getValue();
    };

    SignatureField.prototype.clear = function() {
      var ref;
      return (ref = this.sig()) != null ? ref.clearCanvas() : void 0;
    };

    return SignatureField;

  })();

  ColumnChartField = (function() {
    function ColumnChartField(opts1) {
      this.opts = opts1;
      this.id = this.opts.id;
      $((function(_this) {
        return function() {
          if (_this.opts.parameters != null) {
            _this.registerChangeEvents();
          }
          if (_this.opts.data != null) {
            return _this.loadData(_this.opts.data);
          } else {
            return _this.reloadCurrent();
          }
        };
      })(this));
    }

    ColumnChartField.prototype.ctrl = function() {
      return $$(this.id);
    };

    ColumnChartField.prototype.registerChangeEvents = function() {
      var ab, f, k, len, loader, param, ref, ref1, reload, results;
      loader = (function(_this) {
        return function() {
          return _this.loadFresh();
        };
      })(this);
      reload = _.debounce(loader, 400);
      ref1 = (ref = this.opts) != null ? ref.parameters : void 0;
      results = [];
      for (k = 0, len = ref1.length; k < len; k++) {
        param = ref1[k];
        f = this.getFieldID(param);
        ab = param.auto_bind;
        if (ab !== '0') {
          results.push(ServiceDesk.registerFieldChange(f, (function(_this) {
            return function() {
              return reload();
            };
          })(this)));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    ColumnChartField.prototype.loadFresh = function() {
      var params, url;
      params = this.loadFilterParams();
      url = this.ctrl().attr('view');
      return $.ajax({
        type: 'post',
        url: url,
        data: params,
        success: (function(_this) {
          return function(data) {
            var json_data;
            $(_this).trigger('chart.changed', [_this]);
            json_data = $('<div>' + data + '</div>').find('div').text();
            return _this.loadData(JSON.parse(json_data));
          };
        })(this),
        error: (function(_this) {
          return function(request, status, _e) {
            return console.log('Error', request, status, _e);
          };
        })(this)
      });
    };

    ColumnChartField.prototype.reloadCurrent = function() {
      return this.loadFresh();
    };

    ColumnChartField.prototype.getFieldID = function(parameter) {
      var ref, xf, xs;
      if (parameter.field) {
        return parameter.field;
      }
      xf = parameter.xfield;
      if (!xf) {
        return '';
      }
      xs = (ref = this.opts) != null ? ref.xscope : void 0;
      return $X(xs, xf);
    };

    ColumnChartField.prototype.loadFilterParams = function() {
      var f, k, l, len, len1, n, param, params, ref, ref1, ref2, ref3, ref4, v;
      params = {
        __ajax__: '1',
        __sc__: __token__ || '',
        __colchartmode__: 'data'
      };
      ServiceDesk.fillRemoteCallParams(params);
      ref2 = (ref = (ref1 = this.opts) != null ? ref1.parameters : void 0) != null ? ref : [];
      for (k = 0, len = ref2.length; k < len; k++) {
        param = ref2[k];
        f = this.getFieldID(param);
        n = param.name;
        v = param.value;
        if (f && n) {
          params[n] = xstr(v);
          ServiceDesk.gatherFieldValues(f, n, params);
        }
        if (n && v) {
          params[n] = v;
        }
      }
      ref4 = (ref3 = this.parametersRequiredFuncs) != null ? ref3 : [];
      for (l = 0, len1 = ref4.length; l < len1; l++) {
        f = ref4[l];
        f(param);
      }
      return params;
    };

    ColumnChartField.prototype.loadData = function(data) {
      var highchartsOptions;
      Highcharts.Theme = ChartThemes.defaultTheme();
      highchartsOptions = Highcharts.setOptions(Highcharts.Theme);
      return this.renderChart(data);
    };

    ColumnChartField.prototype.getSingleColumnData = function(series, yaxis_list) {
      var k, len, point, ref, series_list;
      yaxis_list.push(series.yaxis);
      series_list = [];
      ref = series.data;
      for (k = 0, len = ref.length; k < len; k++) {
        point = ref[k];
        series_list.push({
          name: point.label,
          type: series.type,
          data: [point.value],
          tooltips: [point.tooltip],
          yAxis: 0,
          foo: 'bar'
        });
      }
      console.log(series_list);
      return series_list;
    };

    ColumnChartField.prototype.getSeriesData = function(data, yaxis_list) {
      var d, k, len, ref, series, series_list;
      series_list = [];
      for (k = 0, len = data.length; k < len; k++) {
        series = data[k];
        if (ref = series.yaxis, indexOf.call(yaxis_list, ref) < 0) {
          yaxis_list.push(series.yaxis);
        }
        series_list.push({
          name: series.name,
          type: series.type,
          data: (function() {
            var l, len1, ref1, results;
            ref1 = series.data;
            results = [];
            for (l = 0, len1 = ref1.length; l < len1; l++) {
              d = ref1[l];
              results.push(d.value);
            }
            return results;
          })(),
          tooltips: (function() {
            var l, len1, ref1, results;
            ref1 = series.data;
            results = [];
            for (l = 0, len1 = ref1.length; l < len1; l++) {
              d = ref1[l];
              results.push(d.tooltip);
            }
            return results;
          })(),
          yAxis: yaxis_list.indexOf(series.yaxis),
          foo: 'bar'
        });
      }
      return series_list;
    };

    ColumnChartField.prototype.renderChart = function(data) {
      var a, chart, i, self, series_list, single_mode, yaxis_list;
      self = this;
      yaxis_list = [];
      series_list = [];
      single_mode = false;
      if (data.length === 1 && data[0].type === 'column') {
        series_list = this.getSingleColumnData(data[0], yaxis_list);
        single_mode = true;
      } else {
        series_list = this.getSeriesData(data, yaxis_list);
      }
      return chart = $$(this.id).highcharts({
        chart: {
          type: 'column'
        },
        title: {
          text: null
        },
        yAxis: (function() {
          var k, len, results;
          results = [];
          for (i = k = 0, len = yaxis_list.length; k < len; i = ++k) {
            a = yaxis_list[i];
            results.push({
              title: {
                text: a
              },
              labels: {
                enabled: true
              },
              opposite: i % 2 === 1
            });
          }
          return results;
        })(),
        tooltip: {
          useHTML: true,
          formatter: function() {
            var tooltip;
            tooltip = series_list[this.series._i].tooltips[this.key];
            return tooltip;
          }
        },
        plotOptions: {
          series: {
            dataLabels: {
              enabled: false,
              useHTML: true,
              style: {
                color: "inherit",
                fontWeight: "bold",
                fontSize: "12px",
                fontFamily: "AvenirNext"
              },
              inside: false,
              verticalAlign: "bottom"
            },
            pointPadding: single_mode ? 0.0 : 0.0,
            groupPadding: single_mode ? 0.0 : 0.1,
            borderWidth: 0
          }
        },
        series: series_list
      });
    };

    return ColumnChartField;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.CellListField = CellListField;

  root.SignatureField = SignatureField;

  root.ColumnChartField = ColumnChartField;

}).call(this);
