// Generated by CoffeeScript 1.12.4
(function() {
  var autoResize, click_handler, distributeApps, resetAppList, root, saveAppList, setColorScheme, setupAppSort, setupChartDefaults, setupColorSchemeEditor, setupDocGenerator, setupMobileAppMenu, wireupAppListEvents;

  setColorScheme = function(elm, scheme) {
    var i, j;
    for (i = j = 1; j <= 13; i = ++j) {
      elm.removeClass('colorscheme' + i);
    }
    return elm.addClass(scheme);
  };

  click_handler = ($.supportsTouch() && 'touchstart') || 'click';

  autoResize = !isMobileWidth();

  resetAppList = function() {
    var done, err;
    err = function(msg) {
      return alert('An error occurred: ' + msg);
    };
    done = function(content) {
      var drawer, main, originalDrawer, originalMain, r;
      r = $(content);
      main = $(content).find('ul.applist.main');
      drawer = $(content).find('ul.applist.drawer');
      originalMain = $('.applist.main');
      originalDrawer = $('.applist.drawer');
      originalMain.empty();
      originalDrawer.empty();
      main.find('li').appendTo(originalMain);
      drawer.find('li').appendTo(originalDrawer);
      wireupAppListEvents();
      return saveAppList();
    };
    return ServiceDesk.loadView('System', 'defaultappmenu', {}, done, err);
  };

  saveAppList = function() {
    var app_list, j, k, len, len1, li, ref, ref1;
    app_list = [];
    ref = $('.applist.main').children('li');
    for (j = 0, len = ref.length; j < len; j++) {
      li = ref[j];
      if ($(li).attr('app') === '#more') {
        continue;
      }
      app_list.push($(li).attr('app'));
    }
    ref1 = $('.applist.drawer').children('li');
    for (k = 0, len1 = ref1.length; k < len1; k++) {
      li = ref1[k];
      app_list.push($(li).attr('app'));
    }
    UserPrefs.setData('applist', app_list);
    return distributeApps();
  };

  distributeApps = function() {
    var _li, availableHeight, current, drawer, elements, hasMore, i, j, k, l, len, len1, len2, li, max, more, next, ref, ref1, topHeight;
    elements = [];
    more = null;
    ref = $('.applist.main').children('li');
    for (j = 0, len = ref.length; j < len; j++) {
      li = ref[j];
      if ($(li).attr('app') === '#more') {
        more = $(li);
        continue;
      }
      elements.push(li);
    }
    ref1 = $('.applist.drawer').children('li');
    for (k = 0, len1 = ref1.length; k < len1; k++) {
      li = ref1[k];
      elements.push(li);
    }
    $(elements).remove();
    current = $('.applist.main');
    drawer = next = $('.applist.drawer');
    max = xint(current.attr('max'));
    if (autoResize && current.exists()) {
      topHeight = current.data('top-height');
      if (topHeight == null) {
        topHeight = current.offset().top;
        current.data('top-height', topHeight);
      }
      availableHeight = $(window).height() - topHeight;
      max = Math.floor(availableHeight / 62) - 1;
      if (max < 6) {
        max = 6;
      }
    }
    i = 0;
    hasMore = false;
    for (l = 0, len2 = elements.length; l < len2; l++) {
      _li = elements[l];
      li = $(_li);
      current.append(li);
      i += 1;
      if (i >= max && current !== next) {
        current.append(more);
        current = next;
        hasMore = true;
      }
    }
    if (hasMore) {
      return more != null ? more.makeVisible() : void 0;
    } else {
      return more != null ? more.makeInvisible() : void 0;
    }
  };

  wireupAppListEvents = function() {
    return $('.applist').find('li.more a').touchClick(function(evnt) {
      var item;
      evnt.preventDefault();
      item = $(this).closest('li.more');
      if (item.hasClass('expanded')) {
        return ServiceDesk.hideExtendedAppList(evnt.target);
      } else {
        ServiceDesk.showExtendedAppList(evnt.target);
        return i_a.track('Expand Menu', {
          count: elements.length
        });
      }
    });
  };

  setupAppSort = function() {
    var distributer, resizer;
    resizer = function() {
      distributeApps();
      return ServiceDesk.hideExtendedAppList();
    };
    distributer = _.throttle(resizer, 500, {
      leading: true
    });
    if (autoResize) {
      $(window).resize(function() {
        return distributer();
      });
      distributeApps();
    }
    $('.applist.main').sortable({
      items: "li:not(.notsortable)",
      connectWith: '.applist.drawer',
      zIndex: 25,
      stop: function() {
        saveAppList();
        return i_a.track('Sort App Menu', {
          drawer: false
        });
      }
    });
    $('.applist.drawer').sortable({
      items: "li:not(.notsortable)",
      connectWith: '.applist.main',
      zIndex: 25,
      start: function() {
        return $('.appdrawer').addClass('sorting');
      },
      stop: function() {
        saveAppList();
        $('.appdrawer').removeClass('sorting');
        return i_a.track('Sort App Menu', {
          drawer: true
        });
      }
    });
    $('.applist').sortable('disable');
    return wireupAppListEvents();
  };

  setupColorSchemeEditor = function() {
    return $('.color-scheme-editor').live(click_handler, function(evnt) {
      var css, dv, i, j, li, pos, ul, weblet;
      evnt.stopPropagation();
      evnt.preventDefault();
      dv = $$('scheme-bubble');
      if (!dv.exists()) {
        dv = $('<div id="scheme-bubble" />');
        dv.addClass('bubble');
        ul = $('<ul />').appendTo(dv);
        for (i = j = 1; j <= 12; i = ++j) {
          css = 'colorscheme' + i;
          li = $('<li />').addClass(css).text(' ');
          ul.append(li);
          li.attr('scheme', css);
          li.touchClick(function(_e) {
            var scheme, w;
            _e.stopPropagation();
            _e.preventDefault();
            scheme = $(this).attr('scheme');
            w = dv.data('weblet');
            setColorScheme(w, scheme);
            i_a.track('Color Scheme Change', {
              'scheme': scheme
            });
            return $(ServiceDesk).trigger('colorscheme.changed', [w, scheme]);
          });
        }
        $('body').append(dv);
      }
      pos = $(this).offset();
      dv.css({
        left: pos.left,
        top: pos.top + $(this).height()
      });
      weblet = $(this).parents('.color-scheme-editable');
      dv.data('weblet', weblet);
      return dv.css('visibility', 'visible');
    });
  };

  setupMobileAppMenu = function() {
    return $('.applisticon').touchClick(function(e) {
      var fullmenu, main_menu, second_menu, visible;
      e.preventDefault();
      fullmenu = $('#fullappmenu');
      if (!fullmenu.exists()) {
        fullmenu = $('<div />').attr('id', 'fullappmenu').addClass(' bubble');
        fullmenu.css('visibility', 'hidden');
        main_menu = $('.applist.main').clone();
        fullmenu.append(main_menu);
        second_menu = $('.applist.drawer').clone();
        fullmenu.find('.applist').append(second_menu.children('li'));
        fullmenu.find('.more').remove();
        $('body').append(fullmenu);
      }
      visible = !fullmenu.css('visibility') === 'hidden';
      return _.defer(function() {
        if (visible) {
          return fullmenu.css('visibility', 'hidden');
        } else {
          return fullmenu.css('visibility', 'visible');
        }
      });
    });
  };

  setupDocGenerator = function() {
    return $('body').on('click', '.js-doc-gen', function(evnt) {
      evnt.preventDefault();
      return _.defer((function(_this) {
        return function() {
          var appender, e, fd, item, j, len, sp, table, tbody, tr, word_table;
          sp = $(_this).find('.jsdoc').text();
          if (!sp) {
            alert('No field data found');
            return;
          }
          try {
            fd = JSON.parse(sp);
            word_table = $('.word-table');
            if (!word_table.exists()) {
              word_table = $('<div />');
              word_table.addClass('word-table bubble');
              $('body').append(word_table);
              word_table.css({
                position: 'fixed',
                top: '0px',
                left: '0px',
                width: '500px',
                padding: '9px',
                height: '300px',
                overflow: 'auto',
                'z-index': 50002,
                'background-color': 'white'
              });
            }
            table = $('<table \n    style=\'width:100%;color:black;font-family: Verdana;font-size: 14px;border:1px solid gray;border-collapse:collapse;\'>\n<thead>\n<tr style=\'font-weight:bold;background-color:#CCC;border: 1px solid gray;\'>\n<td style="border:1px solid gray;">Field</td>\n<td style="border:1px solid gray;">Type</td>\n<td style="border:1px solid gray;">Description</td>\n</tr>\n</thead>\n<tbody>\n</tbody>\n</table>');
            tbody = table.find('tbody');
            for (j = 0, len = fd.length; j < len; j++) {
              item = fd[j];
              tr = $('<tr style="background-color: white;border-bottom: 1px solid gray;" />');
              appender = function(txt) {
                var td;
                td = $('<td style="border: 1px solid gray;" />');
                td.text(txt);
                return tr.append(td);
              };
              appender(item.label);
              appender(item.type + (!!item.subtype ? ' - ' + item.subtype : ''));
              appender(item.description);
              tbody.append(tr);
            }
            word_table.empty().append(table);
            return word_table.css('visibility', 'visible');
          } catch (error) {
            e = error;
            alert('Unable to read field data');
            throw e;
          }
        };
      })(this));
    });
  };

  setupChartDefaults = function() {
    var e, lang;
    try {
      lang = {
        noData: $L('sys.chart-no-data')
      };
      return Highcharts.setOptions({
        lang: lang
      });
    } catch (error) {
      e = error;
      return console.log('Error initing highcharts', e);
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.ServiceDesk.setColorScheme = setColorScheme;

  root.ServiceDesk.resetAppList = resetAppList;

  $(function() {
    setupColorSchemeEditor();
    setupAppSort();
    setupMobileAppMenu();
    ServiceDesk.updateNotificationStatus();
    setupChartDefaults();
    return setupDocGenerator();
  });

}).call(this);
