// Generated by CoffeeScript 1.12.4
(function() {
  var ANIMATION_CURVE, ANIMATION_TIMEOUT, HOTSPOT_HEIGHT, HOTSPOT_WIDTH, MAX_WEBLETS_PER_ROW, SHOW_HOTSPOTS, WEBLET_HITAREA, WebletBrowser, WebletContainer, hittest, jeq, nudgeLeft, nudgeRight, parametersKeyed, removeNudge, root, updateWeblet, xint,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  MAX_WEBLETS_PER_ROW = 4;

  HOTSPOT_WIDTH = 20;

  HOTSPOT_HEIGHT = 50;

  WEBLET_HITAREA = 0.7;

  SHOW_HOTSPOTS = false;

  ANIMATION_TIMEOUT = 600;

  ANIMATION_CURVE = 'easeOutQuint';

  xint = function(x) {
    if (x == null) {
      return 0;
    }
    return Number(x);
  };

  jeq = function(a, b) {
    if (a == null) {
      return false;
    }
    if (b == null) {
      return false;
    }
    return a.get(0) === b.get(0);
  };

  hittest = function(hotspot, w, elm) {
    var hl;
    hl = hotspot.left;
    if (typeof hl === 'string') {
      if (hl[hl.length - 1] !== '%') {
        return false;
      }
      hl = xnum(hl.substring(0, hl.length - 1));
      hl = elm.parent().width() * hl / 100.0;
    }
    if (typeof hl === 'undefined') {
      if (hotspot.right == null) {
        console.log('Warning: no left or right defined for hotspot');
      }
      hl = elm.parent().width() - hotspot.right - hotspot.width;
    }
    if (hl < w.left && (hl + hotspot.width) < w.left) {
      return false;
    }
    if (hl > w.left + w.width) {
      return false;
    }
    if (hotspot.top < w.top && (hotspot.top + hotspot.height) < w.top) {
      return false;
    }
    if (hotspot.top > w.top + w.height) {
      return false;
    }
    return true;
  };

  removeNudge = function(elm) {
    var left;
    if (elm == null) {
      return;
    }
    if (elm.hasClass('nudgeleft')) {
      elm.removeClass('nudgeleft');
      left = elm.position().left + 10;
      elm.css('left', left);
    }
    if (elm.hasClass('nudgeright')) {
      elm.removeClass('nudgeright');
      left = elm.position().left - 10;
      return elm.css('left', left);
    }
  };

  nudgeLeft = function(elm) {
    if (elm == null) {
      return;
    }
    if (elm.hasClass('nudgeleft')) {
      return;
    }
    elm.css('left', elm.position().left - 10);
    return elm.addClass('nudgeleft');
  };

  nudgeRight = function(elm) {
    if (elm == null) {
      return;
    }
    if (elm.hasClass('nudgeright')) {
      return;
    }
    elm.css('left', elm.position().left + 10);
    return elm.addClass('nudgeright');
  };

  parametersKeyed = function(obj) {
    var k, keys, len, m, r, ref, v;
    if (obj == null) {
      return '';
    }
    keys = (function() {
      var results;
      results = [];
      for (k in obj) {
        v = obj[k];
        results.push(k);
      }
      return results;
    })();
    keys.sort();
    r = '';
    for (m = 0, len = keys.length; m < len; m++) {
      k = keys[m];
      r += '[' + k + ':' + ((ref = obj[k]) != null ? ref : '') + ']';
    }
    return r;
  };

  WebletContainer = (function() {
    WebletContainer.updateWeblet = function(el, opts) {
      return updateWeblet(el, opts);
    };

    function WebletContainer(el, deletable) {
      var rw, self, st;
      this.deletable = deletable != null ? deletable : false;
      self = this;
      this.isWebletContainer = true;
      this.saveUserPref = true;
      this.browsers = [];
      this.el = $(el);
      this.grid = [];
      this.hotspots = [];
      this.defaultRowCount = 2;
      $((function(_this) {
        return function() {
          var bottom_spot;
          bottom_spot = $('.emptyrow', _this.el);
          if (!bottom_spot.length) {
            bottom_spot = $('<div />').addClass('emptyrow');
            _this.el.append(bottom_spot);
          }
          _this.bindWeblets($('.weblet', _this.el));
          return _this.arrangeWeblets();
        };
      })(this));
      st = (function(_this) {
        return function() {
          return _this.save();
        };
      })(this);
      this.throttledSave = _.throttle(st, 5000, {
        leading: false
      });
      $(ServiceDesk).bind('page.openedit', (function(_this) {
        return function() {
          return _this.setEditMode(true);
        };
      })(this));
      $(ServiceDesk).bind('page.closeedit', (function(_this) {
        return function() {
          _this.setEditMode(false);
          return _this.save();
        };
      })(this));
      rw = (function(_this) {
        return function() {
          return _this.arrangeWeblets();
        };
      })(this);
      this.rearrangeWeblets = _.throttle(rw, 300, {
        leading: false
      });
      if (typeof window !== "undefined" && window !== null) {
        $(window).resize((function(_this) {
          return function() {
            return _this.rearrangeWeblets();
          };
        })(this));
      }
      this.el.bind('tabselected', (function(_this) {
        return function() {
          return _this.rearrangeWeblets();
        };
      })(this));
    }

    WebletContainer.getCurrentWebletSize = function(el) {
      var i, m, parent, ref, size;
      parent = $(el).parents('.weblet');
      size = 1;
      for (i = m = 1, ref = MAX_WEBLETS_PER_ROW + 1; 1 <= ref ? m <= ref : m >= ref; i = 1 <= ref ? ++m : --m) {
        if (parent.hasClass('w' + i)) {
          size = i;
          break;
        }
      }
      return MAX_WEBLETS_PER_ROW + 1 - size;
    };

    WebletContainer.prototype.addBrowser = function(browser) {
      return this.browsers.push(browser);
    };

    WebletContainer.prototype.bindWeblets = function(weblets) {
      var self;
      self = this;
      $(weblets).draggable({
        handle: '.header',
        zIndex: 100,
        start: function() {
          return $(this).addClass('dragging');
        },
        stop: function() {
          var hi, hotspot, index, new_row;
          $(this).removeClass('dragging');
          hi = $(this).data('hotspot-index');
          if (hi != null) {
            index = xint(hi);
            hotspot = self.hotspots[index];
            if (hotspot != null) {
              self.insertAtHotSpot($(this), hotspot);
            }
          } else {
            new_row = $(this).data('hotspot-new-row');
            if (new_row != null) {
              $(this).attr('weblet-col', 0).attr('weblet-row', self.grid.length);
            }
          }
          self.arrangeWeblets();
          return self.throttledSave();
        },
        drag: function(evnt, ui) {
          return self.dragOver($(this), ui.position);
        },
        snap: '.webletrow',
        snapMode: 'inner'
      });
      $('.weblet-settings', weblets).touchClick(function(evnt) {
        var content, settings, weblet, width;
        evnt.preventDefault();
        weblet = $(this).parents('.weblet');
        content = weblet.find('.content');
        settings = weblet.find('.settings');
        if (content.position().left < 0) {
          content.animate({
            left: 0
          }, ANIMATION_TIMEOUT, ANIMATION_CURVE);
          return settings.animate({
            left: weblet.width()
          }, ANIMATION_TIMEOUT, ANIMATION_CURVE);
        } else {
          width = settings.width();
          if (width > weblet.width() - 27) {
            width = weblet.width() - 27;
          }
          content.animate({
            left: -width
          }, ANIMATION_TIMEOUT, ANIMATION_CURVE);
          return settings.animate({
            left: weblet.width() - width
          }, ANIMATION_TIMEOUT, ANIMATION_CURVE);
        }
      });
      return $('.weblet-remove', weblets).touchClick(function(evnt) {
        var weblet;
        evnt.preventDefault();
        weblet = $(this).parents('.weblet');
        return self.removeWeblet(weblet);
      });
    };

    WebletContainer.prototype.syncBrowsers = function() {
      var browser, card, key, len, m, ref, results, webletmap;
      webletmap = {};
      $(this.el).find('.weblet').each(function() {
        var key, ref;
        key = $(this).attr('app') + ':' + $(this).attr('view') + ':' + xstr((ref = $(this).attr('webletparamskey')) != null ? ref : '');
        console.log('KEY', key);
        return webletmap[key] = 1;
      });
      ref = this.browsers;
      results = [];
      for (m = 0, len = ref.length; m < len; m++) {
        browser = ref[m];
        results.push((function() {
          var len1, n, ref1, results1;
          ref1 = browser.cards();
          results1 = [];
          for (n = 0, len1 = ref1.length; n < len1; n++) {
            card = ref1[n];
            card = $(card);
            key = card.attr('app') + ':' + card.attr('view') + ':' + parametersKeyed(card.data('webletparams'));
            console.log('KEY2', key);
            results1.push(browser.setCardAvailability(card, webletmap[key] != null));
          }
          return results1;
        })());
      }
      return results;
    };

    WebletContainer.prototype.dragOver = function(elm, pos) {
      var bottom, bottom_piece, first, h, hi, l, len, m, r, rect, ref, ref1, ref2, row, w, weblets;
      pos = elm.position();
      pos.width = elm.width();
      pos.height = elm.height();
      rect = {
        left: pos.left + pos.width * (1 - WEBLET_HITAREA) * 0.5,
        width: pos.width * WEBLET_HITAREA,
        top: pos.top + pos.height * (1 - WEBLET_HITAREA) * 0.5,
        height: pos.height * WEBLET_HITAREA
      };
      ref = this.hotspots;
      for (hi = m = 0, len = ref.length; m < len; hi = ++m) {
        ref1 = ref[hi], h = ref1[0], l = ref1[1], r = ref1[2];
        if (jeq(l, elm) || jeq(r, elm)) {
          elm.removeData('hotspot-index');
          removeNudge(l);
          removeNudge(r);
          continue;
        }
        first = l || r;
        row = xint(first.attr('weblet-row'));
        weblets = this.grid[row];
        if ((weblets != null ? weblets.length : void 0) >= MAX_WEBLETS_PER_ROW && !(ref2 = elm.get(0), indexOf.call((function() {
          var len1, n, results;
          results = [];
          for (n = 0, len1 = weblets.length; n < len1; n++) {
            w = weblets[n];
            results.push(w.get(0));
          }
          return results;
        })(), ref2) >= 0)) {
          continue;
        }
        if (!hittest(h, rect, elm)) {
          removeNudge(l);
          removeNudge(r);
          continue;
        }
        elm.data('hotspot-index', hi);
        if (l !== null) {
          nudgeLeft(l);
        }
        if (r !== null) {
          nudgeRight(r);
        }
        return;
      }
      bottom_piece = $('.emptyrow', this.el);
      bottom = bottom_piece.position();
      bottom.width = bottom_piece.width();
      bottom.height = bottom_piece.height();
      if (hittest(bottom, rect, elm)) {
        bottom_piece.addClass('drop');
        return elm.data('hotspot-new-row', 1);
      } else {
        bottom_piece.removeClass('drop');
        return elm.removeData('hotspot-new-row');
      }
    };

    WebletContainer.prototype.arrangeWebletsMobile = function() {
      var cls, j, len, m, new_cls, new_col_size, old_cls, old_col_size, ref, results, row, weblet, weblets, y;
      y = 0;
      new_cls = 4;
      ref = this.grid;
      results = [];
      for (row = m = 0, len = ref.length; m < len; row = ++m) {
        weblets = ref[row];
        results.push((function() {
          var len1, n, o, ref1, results1;
          results1 = [];
          for (n = 0, len1 = weblets.length; n < len1; n++) {
            weblet = weblets[n];
            weblet.draggable('disable');
            old_cls = -1;
            for (j = o = 0, ref1 = MAX_WEBLETS_PER_ROW; 0 <= ref1 ? o <= ref1 : o >= ref1; j = 0 <= ref1 ? ++o : --o) {
              cls = 'w' + (j + 1);
              if (weblet.hasClass(cls)) {
                old_cls = j + 1;
                weblet.removeClass(cls);
              }
            }
            weblet.addClass('w' + new_cls);
            if (old_cls !== new_cls) {
              new_col_size = MAX_WEBLETS_PER_ROW + 1 - new_cls;
              old_col_size = MAX_WEBLETS_PER_ROW + 1 - old_cls;
              $('.forweblet', weblet).trigger('webletsizechanged', [new_col_size, old_col_size]);
            }
            weblet.css({
              left: '0px',
              top: y
            });
            y += weblet.height();
            weblet.find('.settings').css('left', weblet.width());
            results1.push(weblet.find('.content').css('left', 0));
          }
          return results1;
        })());
      }
      return results;
    };

    WebletContainer.prototype.setRefresh = function(interval) {
      var refresher;
      if (this.refreshTimer != null) {
        clearTimeout(this.refreshTimer);
      }
      this.timeoutInterval = interval;
      if (interval === 0) {
        return;
      }
      refresher = (function(_this) {
        return function() {
          return _this.refreshWeblets(function() {
            return _this.refreshTimer = setTimeout(refresher, interval);
          });
        };
      })(this);
      return this.refreshTimer = setTimeout(refresher, interval);
    };

    WebletContainer.prototype.refreshWeblets = function(finished) {
      var doneCount, el, staggeredTimeout, timeout, updateWebletStaggered, webletCount, weblets;
      timeout = this.timeoutInterval;
      weblets = (function() {
        var len, m, ref, results;
        ref = $('.weblet', this.el);
        results = [];
        for (m = 0, len = ref.length; m < len; m++) {
          el = ref[m];
          results.push($(el));
        }
        return results;
      }).call(this);
      if (weblets.length === 0) {
        finished();
        return;
      }
      webletCount = weblets.length;
      doneCount = 0;
      staggeredTimeout = 500;
      updateWebletStaggered = function(_weblets) {
        var done, updater, weblet;
        weblet = _weblets.shift();
        if (weblet == null) {
          return;
        }
        done = function() {
          doneCount += 1;
          if (doneCount >= webletCount) {
            return finished();
          }
        };
        updater = function() {
          WebletContainer.updateWeblet(weblet, {
            nohighlight: true,
            done: done
          });
          return updateWebletStaggered(_weblets);
        };
        return setTimeout(updater, staggeredTimeout);
      };
      return updateWebletStaggered(weblets);
    };

    WebletContainer.prototype.normalizeGrid = function(grid) {
      var i, m, maxRow, orphanedItems, ref, results, row, weblet, weblets;
      orphanedItems = [];
      maxRow = -1;
      for (row in grid) {
        weblets = grid[row];
        row = xint(row);
        if (row > maxRow) {
          maxRow = row;
        }
        while (weblets.length > MAX_WEBLETS_PER_ROW) {
          orphanedItems.push(weblets.pop());
        }
        while (weblets.length < MAX_WEBLETS_PER_ROW) {
          weblet = orphanedItems.shift();
          if (weblet == null) {
            break;
          }
          weblets.push(weblet);
        }
      }
      if (orphanedItems.length > 0) {
        for (i = m = 0, ref = maxRow; 0 <= ref ? m <= ref : m >= ref; i = 0 <= ref ? ++m : --m) {
          weblets = grid[row];
          if (weblets == null) {
            grid[row] = [];
          }
          while (weblets.length < MAX_WEBLETS_PER_ROW) {
            weblets.push(orphanedItems.shift());
          }
        }
      }
      i = 1;
      results = [];
      while (orphanedItems.length > 0) {
        grid[maxRow + i] = [orphanedItems.shift()];
        results.push(i += 1);
      }
      return results;
    };

    WebletContainer.prototype.arrangeWeblets = function() {
      var _c, _grid, _r, a, b, cls, el, empty_row, h, hotspot, hotspot_height, hotspot_width, i, j, key, keys, len, len1, len2, len3, len4, m, n, new_cls, new_col_size, o, offset, old_cls, old_col_size, pos, q, ref, ref1, ref2, ref3, results, roffset, row, s, self, u, w, weblets;
      self = this;
      hotspot_width = HOTSPOT_WIDTH;
      hotspot_height = HOTSPOT_HEIGHT;
      this.grid = [];
      _grid = {};
      $('.weblet', this.el).each(function() {
        var col, row, weblet;
        weblet = $(this);
        weblet.removeData('hotspot-index');
        weblet.removeClass('nudgeleft nudgeright');
        row = xint(weblet.attr('weblet-row'));
        col = weblet.attr('weblet-col');
        if (_grid[row] == null) {
          _grid[row] = [];
        }
        return _grid[row].push(weblet);
      });
      console.log(_grid);
      keys = _.sortBy(_.keys(_grid), function(x) {
        return xint(x);
      });
      for (_r = m = 0, len = keys.length; m < len; _r = ++m) {
        key = keys[_r];
        weblets = _.sortBy(_grid[key], function(x) {
          return xint(x.attr('weblet-col'));
        });
        for (_c = n = 0, len1 = weblets.length; n < len1; _c = ++n) {
          w = weblets[_c];
          $(w).attr('weblet-col', _c).attr('weblet-row', _r);
        }
        this.grid.push(weblets);
      }
      if (isMobileWidth()) {
        this.arrangeWebletsMobile();
        return;
      }
      this.hotspots = [];
      ref = this.grid;
      for (row = o = 0, len2 = ref.length; o < len2; row = ++o) {
        weblets = ref[row];
        offset = 0;
        for (i = q = 0, len3 = weblets.length; q < len3; i = ++q) {
          w = weblets[i];
          old_cls = -1;
          for (j = s = 0, ref1 = MAX_WEBLETS_PER_ROW; 0 <= ref1 ? s <= ref1 : s >= ref1; j = 0 <= ref1 ? ++s : --s) {
            cls = 'w' + (j + 1);
            if (w.hasClass(cls)) {
              old_cls = j + 1;
              w.removeClass(cls);
            }
          }
          new_cls = weblets.length;
          w.addClass('w' + new_cls);
          w.find('.settings').css('left', w.width());
          w.find('.content').css('left', 0);
          if (new_cls !== old_cls) {
            new_col_size = MAX_WEBLETS_PER_ROW + 1 - new_cls;
            old_col_size = -1;
            if (old_cls > 0) {
              old_col_size = MAX_WEBLETS_PER_ROW + 1 - old_cls;
            }
            $('.forweblet', w).trigger('webletsizechanged', [new_col_size, old_col_size]);
          }
          roffset = (i * 100.0 / weblets.length) + '%';
          pos = {
            'left': roffset,
            'top': row * w.height(),
            'width': w.width(),
            'height': w.height()
          };
          w.css({
            left: pos.left,
            top: pos.top,
            top: row * w.height()
          });
          w.draggable('enable');
          offset += w.width();
          if (i === 0) {
            hotspot = {
              left: pos.left,
              width: hotspot_width * 0.5,
              top: pos.top + pos.height * 0.5 - hotspot_height * 0.5,
              height: hotspot_height
            };
            this.hotspots.push([hotspot, null, w]);
          } else {
            hotspot = {
              left: pos.left,
              width: hotspot_width,
              top: pos.top + pos.height * 0.5 - hotspot_height * 0.5,
              height: hotspot_height
            };
            this.hotspots.push([hotspot, weblets[i - 1], w]);
          }
          if (i === weblets.length - 1) {
            hotspot = {
              right: 0,
              width: hotspot_width * 0.5,
              top: pos.top + pos.height * 0.5 - hotspot_height * 0.5,
              height: hotspot_height
            };
            this.hotspots.push([hotspot, w, null]);
          }
        }
        empty_row = $('.emptyrow', this.el);
        empty_row.css({
          left: '0px',
          top: w.height() * (row + 1)
        });
        empty_row.removeClass('drop');
      }
      if (SHOW_HOTSPOTS) {
        $('.hotspot', this.el).remove();
        ref2 = this.hotspots;
        results = [];
        for (u = 0, len4 = ref2.length; u < len4; u++) {
          ref3 = ref2[u], h = ref3[0], a = ref3[1], b = ref3[2];
          el = $('<div />').addClass('hotspot');
          el.css(h);
          results.push(this.el.append(el));
        }
        return results;
      }
    };

    WebletContainer.prototype.insertAtHotSpot = function(weblet, hotspot) {
      var col, h, i, insert_right, len, m, results, row, w, weblets;
      if (weblet == null) {
        return;
      }
      if (hotspot == null) {
        return;
      }
      insert_right = true;
      h = hotspot[1];
      if (h == null) {
        h = hotspot[2];
        insert_right = false;
      }
      if (h == null) {
        console.error('Invalid hotspot', hotspot, weblet);
        return;
      }
      row = xint(h.attr('weblet-row'));
      weblets = this.grid[row];
      if (weblets == null) {
        console.error('No weblets in grid', this.grid, row, hotspot, weblet);
        return;
      }
      col = xint(h.attr('weblet-col'));
      i = _.indexOf((function() {
        var len, m, results;
        results = [];
        for (m = 0, len = weblets.length; m < len; m++) {
          w = weblets[m];
          results.push(w.get(0));
        }
        return results;
      })(), weblet.get(0));
      if (i >= 0) {
        if (i <= col) {
          col -= 1;
        }
        weblets.splice(i, 1);
      }
      if (insert_right) {
        col += 1;
      }
      weblets.splice(col, 0, weblet);
      weblet.attr('weblet-row', row);
      results = [];
      for (i = m = 0, len = weblets.length; m < len; i = ++m) {
        w = weblets[i];
        results.push(w.attr('weblet-col', i));
      }
      return results;
    };

    WebletContainer.prototype.printGrid = function() {
      var len, m, ref, results, row, w, weblets;
      ref = this.grid;
      results = [];
      for (row = m = 0, len = ref.length; m < len; row = ++m) {
        weblets = ref[row];
        results.push((function() {
          var len1, n, results1;
          results1 = [];
          for (n = 0, len1 = weblets.length; n < len1; n++) {
            w = weblets[n];
            results1.push(console.log(row, w.get(0)));
          }
          return results1;
        })());
      }
      return results;
    };

    WebletContainer.prototype.removeAllWeblets = function() {
      var len, m, weblet, weblets;
      weblets = this.el.find('.weblet');
      for (m = 0, len = weblets.length; m < len; m++) {
        weblet = weblets[m];
        weblet.remove();
      }
      this.arrangeWeblets();
      return this.syncBrowsers();
    };

    WebletContainer.prototype.removeWeblet = function(app_or_weblet, view, params) {
      var app, weblet;
      if (view == null) {
        view = null;
      }
      if (params == null) {
        params = null;
      }
      if (view !== null) {
        app = app_or_weblet;
        weblet = this.findWeblet(app, view, params);
      } else {
        weblet = app_or_weblet;
      }
      if (weblet == null) {
        return;
      }
      weblet.remove();
      this.arrangeWeblets();
      return this.syncBrowsers();
    };

    WebletContainer.prototype.findSuitableSpace = function() {
      var len, m, ref, row, weblets;
      ref = this.grid;
      for (row = m = 0, len = ref.length; m < len; row = ++m) {
        weblets = ref[row];
        if (weblets.length < this.defaultRowCount) {
          return [row, 1];
        }
      }
      return [200, 200];
    };

    WebletContainer.prototype.loadWeblet = function(app, view, params, colorscheme, cb, scopeparams) {
      if (scopeparams == null) {
        scopeparams = {};
      }
      if (params == null) {
        params = QS();
      }
      params['__webletparams__'] = JSON.stringify(scopeparams != null ? scopeparams : {});
      return ServiceDesk.loadView(app, view, params, (function(_this) {
        return function(html) {
          var allschemes, col, content, existing, newHash, oldHash, ref, ref1, row, scheme, weblet, weblets;
          content = $(html);
          _this.el.append(content);
          weblets = [];
          $(content).each(function() {
            if ($(this).hasClass('weblet')) {
              return weblets.push($(this));
            }
          });
          weblet = $(weblets[0]);
          ref = _this.findSuitableSpace(), row = ref[0], col = ref[1];
          $(weblet).attr('weblet-col', col).attr('weblet-row', row);
          scheme = colorscheme;
          if (!scheme) {
            allschemes = ServiceDesk.getAllColorSchemes();
            existing = [];
            $('.weblet', _this.el).each(function() {
              var es, i, w;
              w = $(this);
              es = ServiceDesk.getColorScheme(w);
              i = _.indexOf(allschemes, es);
              if (i >= 0) {
                Array.remove(allschemes, i);
              }
              return existing.push(es);
            });
            if (allschemes.length === 0) {
              scheme = (ref1 = existing[0]) != null ? ref1 : 'colorscheme1';
            } else {
              scheme = allschemes[0];
            }
          }
          ServiceDesk.setColorScheme($(weblet), scheme);
          _this.setWebletEditMode($(weblet), ServiceDesk.isPageEditMode());
          oldHash = _this.getHash();
          if (!!oldHash) {
            newHash = _this.hash();
            _this.setHash(newHash);
          }
          _this.bindWeblets($(weblet));
          _this.arrangeWeblets();
          _this.syncBrowsers();
          return typeof cb === "function" ? cb(content, $(weblet)) : void 0;
        };
      })(this));
    };

    WebletContainer.prototype.scrollToWeblet = function(weblet) {
      var t;
      t = $(weblet).offset().top;
      return $('body').animate({
        scrollTop: t
      }, 1000);
    };

    WebletContainer.prototype.findWeblet = function(app, view, params) {
      var e, key, keyed, len, m, obj, p, ref, ref1, self, w, wkey;
      if (params == null) {
        params = None;
      }
      key = app + '.' + view;
      if (params) {
        if (typeof params === 'string') {
          try {
            obj = JSON.parse(params);
            keyed = parametersKeyed(obj);
            if (keyed) {
              key += ':' + keyed;
            }
          } catch (error) {
            e = error;
          }
        } else {
          obj = params;
          keyed = parametersKeyed(obj);
          if (keyed) {
            key += ':' + keyed;
          }
        }
      }
      self = this;
      ref = this.el.find('.weblet');
      for (m = 0, len = ref.length; m < len; m++) {
        w = ref[m];
        p = xstr((ref1 = $(w).attr('webletparamskey')) != null ? ref1 : '');
        wkey = $(w).attr('app') + '.' + $(w).attr('view');
        if (p) {
          wkey += ':' + p;
        }
        if (String.matches(key, wkey)) {
          return $(w);
        }
      }
      return null;
    };

    WebletContainer.prototype.webletExists = function(weblet) {
      var app, params, view;
      app = weblet.app;
      view = weblet.view;
      params = weblet.parameters;
      return !!this.findWeblet(app, view, params);
    };

    WebletContainer.prototype.setWebletEditMode = function(weblet, editable) {
      if (editable) {
        $(weblet).find('.weblet-settings').makeInvisible();
        return $(weblet).find('.weblet-remove').makeVisible();
      } else {
        $(weblet).find('.weblet-settings').makeVisible();
        return $(weblet).find('.weblet-remove').makeInvisible();
      }
    };

    WebletContainer.prototype.setEditMode = function(editable) {
      var self;
      self = this;
      if (editable && this.deletable) {
        return this.el.find('.weblet').each(function() {
          return self.setWebletEditMode($(this), true);
        });
      } else {
        return this.el.find('.weblet').each(function() {
          return self.setWebletEditMode($(this), false);
        });
      }
    };

    WebletContainer.prototype.serialize = function() {
      var elements, id;
      id = this.el.attr('id');
      elements = WebletContainer.save(this.el.attr('id'));
      return JSON.stringify(elements);
    };

    WebletContainer.prototype.getHash = function() {
      return this.el.data('weblet-container-hash');
    };

    WebletContainer.prototype.save = function() {
      var datakey, elements, hash, id, key;
      id = this.el.attr('id');
      datakey = this.el.attr('data-key');
      hash = this.getHash();
      elements = WebletContainer.save(this.el.attr('id'));
      key = 'webletcontainer.' + id;
      if (!!hash) {
        key += ':' + hash;
      }
      if (!!datakey) {
        key = datakey;
      }
      console.log('saving weblet', key);
      if (this.saveUserPref) {
        return UserPrefs.setData(key, elements);
      }
    };

    WebletContainer.prototype.setHash = function(newHash) {
      return this.el.data('weblet-container-hash', newHash);
    };

    WebletContainer.prototype.hash = function() {
      return WebletContainer.hash(this.el.attr('id'));
    };

    WebletContainer.save = function(x) {
      var el, parts;
      el = $$(x);
      parts = [];
      $(el).find('.weblet').each(function() {
        var w;
        w = $(this);
        return parts.push({
          app: w.attr('app'),
          view: w.attr('view'),
          row: w.attr('weblet-row'),
          col: w.attr('weblet-col'),
          parameters: ServiceDesk.allScopedParameters(w.attr('xid')),
          colorscheme: ServiceDesk.getColorScheme(w)
        });
      });
      return parts;
    };

    WebletContainer.hash = function(x) {
      var weblet, weblets;
      weblets = (function() {
        var len, m, ref, results;
        ref = WebletContainer.save(x);
        results = [];
        for (m = 0, len = ref.length; m < len; m++) {
          weblet = ref[m];
          results.push(weblet.app.toUpperCase() + '/' + weblet.view.toUpperCase());
        }
        return results;
      })();
      weblets.sort();
      return Sha256.hash(weblets.join(':'));
    };

    return WebletContainer;

  })();

  WebletBrowser = (function() {
    function WebletBrowser(el1, webletContainer) {
      this.el = el1;
      this.webletContainer = webletContainer;
    }

    WebletBrowser.prototype.cards = function() {
      return this.el.find('.webletitem');
    };

    WebletBrowser.prototype.setCardAvailability = function(card, availability) {
      if (availability) {
        card.find('.addweblet').makeInvisible();
        return card.find('.removeweblet').makeVisible();
      } else {
        card.find('.addweblet').makeVisible();
        return card.find('.removeweblet').makeInvisible();
      }
    };

    WebletBrowser.prototype.populateWeblets = function(data) {
      var card, container, e, len, m, url, wc, weblet, webletParams;
      container = this.el;
      wc = this.webletContainer;
      container.empty();
      wc.addBrowser(this);
      if (!data || data.length === 0) {
        container.html('<div class="nodata noweblets">' + $L('sys.weblet-no-matches') + '</div>');
        return;
      }
      for (m = 0, len = data.length; m < len; m++) {
        weblet = data[m];
        card = $('<div class=\'webletitem\'>\n <div class=\'thumbnail\'  ></div>\n <div class=\'title\'></div>\n <div class=\'description\'></div>\n <button class=\'addweblet\'>' + $L('sys.weblet-add-to-dashboard') + '</button>\n<button class=\'removeweblet\'>' + $L('sys.weblet-remove-from-dashboard') + '</button>\n</div> ');
        card.attr('app', weblet.app).attr('view', weblet.view);
        webletParams = {};
        if (weblet.parameters) {
          try {
            webletParams = JSON.parse(weblet.parameters);
          } catch (error) {
            e = error;
            webletParams = {};
          }
        }
        card.data('webletparams', webletParams);
        card.find('.title').text(weblet.title);
        card.find('.description').text(weblet.description);
        url = ServiceDesk.rootUrl(weblet.thumbnail);
        card.find('.thumbnail').css('background-image', 'url(' + url + ')');
        container.append(card);
        if (wc.webletExists(weblet)) {
          card.find('.addweblet').makeInvisible();
        } else {
          card.find('.removeweblet').makeInvisible();
        }
        card.find('.addweblet').touchClick(function(evnt) {
          var app, params, parent, view;
          parent = $(this).parents('.webletitem');
          app = parent.attr('app');
          view = parent.attr('view');
          params = parent.data('webletparams');
          return wc.loadWeblet(app, view, null, null, null, params);
        });
        card.find('.removeweblet').touchClick(function(evnt) {
          var app, params, parent, view;
          parent = $(this).parents('.webletitem');
          app = parent.attr('app');
          view = parent.attr('view');
          params = parent.data('webletparams');
          return wc.removeWeblet(app, view, params);
        });
      }
      return container.parent().scrollLeft(0);
    };

    return WebletBrowser;

  })();

  updateWeblet = function(el, opts) {
    var app, ctrl, customUpdateFields, eld, field, fieldid, fields, len, len1, len2, m, n, o, p, params, ref, results, skip, updateFields, updateViewFields, view, xid;
    el = $(el);
    if (!el.hasClass('weblet')) {
      el = el.parents('.weblet');
      if (!el.exists()) {
        if (opts != null) {
          opts.done();
        }
        return;
      }
    }
    xid = el.attr('xid');
    if (el.data('no-auto-update') === '1') {
      if (opts != null) {
        opts.done();
      }
      return;
    }
    updateFields = xstr(el.data('update-fields'));
    if (updateFields === '') {
      if (opts != null) {
        opts.done();
      }
      return;
    }
    fields = updateFields.split(',');
    if (fields.length === 0) {
      if (opts != null) {
        opts.done();
      }
      return;
    }
    updateViewFields = [];
    customUpdateFields = [];
    for (m = 0, len = fields.length; m < len; m++) {
      fieldid = fields[m];
      ctrl = __Fields__[fieldid];
      if (ctrl == null) {
        ctrl = __SearchTables__[fieldid];
      }
      if (ctrl == null) {
        continue;
      }
      if (ctrl.updateField != null) {
        customUpdateFields.push(ctrl);
      } else {
        updateViewFields.push(fieldid);
      }
    }
    if (updateViewFields.length > 0) {
      skip = false;
      eld = el.get(0);
      ref = $(document.activeElement).parents();
      for (n = 0, len1 = ref.length; n < len1; n++) {
        p = ref[n];
        if (p === eld) {
          console.log(el, 'has focus. Skipping...');
          _.defer(function() {
            return opts != null ? opts.done() : void 0;
          });
          skip = true;
          break;
        }
      }
      if (!skip) {
        app = el.attr('app');
        view = el.attr('view');
        params = QS();
        params.__webletparams__ = JSON.stringify(ServiceDesk.allScopedParameters(xid));
        ServiceDesk.updateFieldsInView(updateViewFields, app, view, params, null, opts);
      }
    }
    results = [];
    for (o = 0, len2 = customUpdateFields.length; o < len2; o++) {
      field = customUpdateFields[o];
      results.push(field.updateField(opts));
    }
    return results;
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.WebletContainer = WebletContainer;

  root.WebletBrowser = WebletBrowser;

}).call(this);
